use inc::Module::JSAN::DSL;

name                JooseIt
version             0.01
    
author              'Nickolay Platonov (aka SamuraiJack) <nplatonov@cpan.org>',
abstract            'Joose.it web-site, written in Symbie framework'
    
license             lgpl
    
requires            Symbie                          0.01
requires            SymbieX.History                 0.01
requires            SymbieX.Template.Shotenjin      0.01
requires            Raphael                         1.2.8

requires            ExtX.Layout                     0.01


docs_markup         mmd