COMPONENTS = {
	"core" : [
		"Test.Run.Result",
		"Test.Run.Result.Diagnostic",
		"Test.Run.Result.Assertion",
		
		"Test.Run.Test",
		"Test.Run.Test.More",
		"Test.Run.Test.Browser",
		
		"Test.Run.Harness",
		"Test.Run.Harness.Browser",
		"Test.Run.Harness.Browser.Single",
		
		"Test.Run.Harness.Browser.Proven",
		
		
		"Test.Run"
	],
	
	"extjs" : [
		"+core",
		
		"Test.Run.Test.Browser.ExtJS",
		
		"Test.Run.Harness.Browser.UI.Viewport",
		"Test.Run.Harness.Browser.UI.TestGrid",
		"Test.Run.Harness.Browser.UI.AssertionGrid",
		
		"Test.Run.Harness.Browser.Multi"
	]
} 

