COMPONENTS = {
    
    "Core" : [
        "JooseIt.Control.NavigationButton",
        
        "JooseIt.Widget.PageReport",
        "JooseIt.Widget.About",
        "JooseIt.Widget.Download",
        "JooseIt.Widget.Footer",
        "JooseIt.Widget.Header",
        "JooseIt.Widget.Home",
        "JooseIt.Widget.NotFound",
        "JooseIt.Widget.Resources",
        
        "JooseIt.Widget.Root",
        
        "JooseIt.Layout.Centered",
        "JooseIt.Layout.Site",
        "JooseIt"
    ],
    
    
    "Bundle" : [
        "jsan:Task.Symbie.ExtJSBundle",
        
        "=static/deps/raphael-min-1.5.0.js",
    
        "jsan:JooseX.Class.Singleton",
        "jsan:Task.ExtX.Shotenjin.Core",
        "jsan:Task.ExtX.Layout.Core",
    
        "+Core"
    ]
} 

