COMPONENTS = {
    
    "Core" : [
        "JooseIt.Control.NavigationButton",
        
        "JooseIt.Widget.PageReport",
        "JooseIt.Widget.About",
        "JooseIt.Widget.Download",
        "JooseIt.Widget.Footer",
        "JooseIt.Widget.Header",
        "JooseIt.Widget.Home",
        "JooseIt.Widget.NotFound",
        "JooseIt.Widget.Resources",
        
        "JooseIt.Widget.Root",
        
        "JooseIt.Layout.Centered",
        "JooseIt.Layout.Site",
        "JooseIt"
    ],
    
    
    "Bundle" : [
        "jsan:Task.Joose.Core"
//        "jsan:Task.JooseX.Attribute.Bootstrap",
//        
//        "jsan:JooseX.SimpleRequest",
//        "jsan:Task.JooseX.Namespace.Depended.Web",
//        
//        "jsan:Task.JooseX.CPS.All",
//        
//        "jsan:JooseX.Class.Singleton",
//        "jsan:JooseX.Meta.Lazy",
//        
//
//        "jsan:JooseX.Bridge.Ext",
//        
//        "jsan:Task.ExtJS.Adapter.Ext",
//        "jsan:JooseX.Bridge.Ext.LazyConvertor",
//        "jsan:Task.ExtJS.All",
//        
//        "jsan:ExtX.Reference.Slot",
//        "jsan:ExtX.Layout.CenterBoth",
//        "jsan:ExtX.Layout.NBSP",
//        "jsan:ExtX.Layout.CenterHorizontally",
//        
////        "jsan:Digest.MD5",
//        
//        "jsan:Task.Symbie.Core",
//        
////        "jsan:Raphael",
//        
//        "jsan:Shotenjin.Joosed.Template",
//        
//        "jsan:Johnny.Mnemonic",
//        "jsan:SymbieX.History.Router",
//        "jsan:Task.SymbieX.Template.Shotenjin.Core",
//        
//        "+Core"
    ]
    
} 

