VERSIONS
========

Joose is currently presented with 2 major releases: Joose 2 and Joose 3

Joose 2
------

Joose 2 is a stable, feature-rich and proven-to-work system. It is in production on several multi M$ sites (in both visitors and revenue), like:

<http://www.tuifly.com/en/>

<http://www.mirapodo.de/>


Joose 3
------

Joose 3 is currently under very active development. It is already stable with about 600 unit tests, though it may miss some features, 
presented in Joose 2 (like type system, serialization and Google Gears support). 

On top of the Joose 2 feature set Joose 3 offers a more to-the-spec implementation of roles based on 
[original traits spec](http://www.iam.unibe.ch/~scg/Research/Traits/), improved namespaces, better meta-roles support and [mutability](http://openjsan.org/go/?l=Joose.Manual.Mutability).

Joose 3 is being distributed via the OpenJSAN platform, which establishes a distribution standard and provides installation tools.

