VERSIONS
========

Joose is currently presented with 2 major releases: Joose2 and Joose3

Joose2
------

Joose2 is a stable, feature-rich and proven-to-work system. It is in production on several multi M$ sites (in both visitors and revenue), like:

<http://www.tuifly.com/>

<http://www.mirapodo.de/>


Joose3
------

Joose3 is currently most active developing version of Joose. Its already stable with about 600 unit tests, though it may miss some features, 
presented in Joose2 (like type system, serialization and Google Gears support). 

Instead of that Joose3 offers some other features, like roles implementation based on 
[original traits spec](http://www.iam.unibe.ch/~scg/Research/Traits/), improved namespaces, better meta-roles support and [mutability](http://openjsan.org/go/?l=Joose.Manual.Mutability).

Joose3 is also distributing via OpenJSAN platform, which establish a distribution standard and provides installation tools.

