Download
========

Joose2
------

The latest release in 2.x series is available here: 

<http://code.google.com/p/joose-js/downloads/list>


Joose3
------

The recommended installation procedure for Joose3 is described here: <http://openjsan.org/go/?l=Joose.Manual.Installation>

Alternatively, the complete list of releases is available here: <http://openjsan.org/go?d=Joose>


Git Repository
==============

To obtain the latest sources, grab a copy of the Joose [repository at github](http://github.com/Joose/Joose)