RESOURCES
=========

Documentation
-------------

### Joose 2 

Manual & Cookbook: <http://code.google.com/p/joose-js/>

### Joose 3 

Manual: <http://openjsan.org/go/?l=Joose.Manual>

Cookbook: <http://openjsan.org/go/?l=Joose.Cookbook>


Community
---------

Mailing list: <http://groups.google.com/group/joose-js>

Forum: <http://joose.it/forum>

IRC: #joose on freenode


Blogs
-----

Malte Ubl: <http://www.nonblocking.io/>



Core extensions
---------------

Singleton pattern: <http://openjsan.org/go/?l=JooseX.Class.Singleton>

Additional features for attributes: <http://openjsan.org/go/?l=JooseX.Attribute>

Dependencies (browser oriented): <http://openjsan.org/go/?l=JooseX.Namespace.Depended>