RESOURCES
=========

Documentation
-------------

### Joose 2 

Manual & Cookbook: <http://code.google.com/p/joose-js/>

### Joose 3 

Manual: <http://bit.ly/joose_manual>

Cookbook: <http://bit.ly/joose_cookbook>


Community
---------

Mailing list: <http://groups.google.com/group/joose-js>

IRC: [#joose](http://webchat.freenode.net/?randomnick=1&channels=joose&prompt=1) on freenode


Blogs
-----

Malte Ubl: <http://www.nonblocking.io/>



Core extensions
---------------

Additional features for attributes: <http://samuraijack.github.com/JooseX-Attribute>

Dependencies (cross-platform): <http://samuraijack.github.com/JooseX-Namespace-Depended>

Singleton pattern: <http://samuraijack.github.com/JooseX-Class-Singleton>

Also see the <http://nodul.es/modules/> for the "JooseX" search term.


