Class('JooseIt.Widget.About', {
    
    isa : 'SymbieX.Template.Shotenjin.Container',
    
    does : [ 'Symbie.Widget', 'JooseIt.Widget.PageReport' ],

    
    have : {
        pageId                  : 'about',
        
        autoHeight              : true,
        
        templateSources         : {
            /*tj:../../../content/About.html
                <h1 id="versions">VERSIONS</h1>
                
                <p>Joose is currently presented with 2 major releases: Joose 2 and Joose 3</p>
                
                <h2 id="joose2">Joose 2</h2>
                
                <p>Joose 2 is a stable, feature-rich and proven-to-work system. It is in production on several multi M$ sites (in both visitors and revenue), like:</p>
                
                <p><a href="http://www.tuifly.com/en/">http://www.tuifly.com/en/</a></p>
                
                <p><a href="http://www.mirapodo.de/">http://www.mirapodo.de/</a></p>
                
                <h2 id="joose3">Joose 3</h2>
                
                <p>Joose 3 is currently under very active development. It is already stable with about 600 unit tests, though it may miss some features, 
                presented in Joose 2 (like type system, serialization and Google Gears support). </p>
                
                <p>On top of the Joose 2 feature set Joose 3 offers a more to-the-spec implementation of roles based on 
                <a href="http://www.iam.unibe.ch/~scg/Research/Traits/">original traits spec</a>, improved namespaces, better meta-roles support and <a href="http://openjsan.org/go/?l=Joose.Manual.Mutability">mutability</a>.</p>
                
                <p>Joose 3 is being distributed via the OpenJSAN platform, which establishes a distribution standard and provides installation tools.</p>
            tj*/

            /* GENERATED BY SHOTENJIN.JOOSED HELPER, DO NOT MODIFY DIRECTLY */
            sources : '<h1 id="versions">VERSIONS</h1>\n<p>Joose is currently presented with 2 major releases: Joose 2 and Joose 3</p>\n<h2 id="joose2">Joose 2</h2>\n<p>Joose 2 is a stable, feature-rich and proven-to-work system. It is in production on several multi M$ sites (in both visitors and revenue), like:</p>\n<p><a href="http://www.tuifly.com/en/">http://www.tuifly.com/en/</a></p>\n<p><a href="http://www.mirapodo.de/">http://www.mirapodo.de/</a></p>\n<h2 id="joose3">Joose 3</h2>\n<p>Joose 3 is currently under very active development. It is already stable with about 600 unit tests, though it may miss some features,\npresented in Joose 2 (like type system, serialization and Google Gears support). </p>\n<p>On top of the Joose 2 feature set Joose 3 offers a more to-the-spec implementation of roles based on\n<a href="http://www.iam.unibe.ch/~scg/Research/Traits/">original traits spec</a>, improved namespaces, better meta-roles support and <a href="http://openjsan.org/go/?l=Joose.Manual.Mutability">mutability</a>.</p>\n<p>Joose 3 is being distributed via the OpenJSAN platform, which establishes a distribution standard and provides installation tools.</p>'
        }
    }
    
})