HISTORY
=======

Based on Moose, which in turn based on best features from Perl6, CLOS, SmallTalk etc.


VERSIONS
========

Joose is currently presented with 2 major releases: Joose2 and Joose3

Joose2
------

Joose2 is a stable, feature-rich and proven-to-work system. It is in production on several multi M$ sites (in both visitors and revenue), like:

<http://www.tuifly.com/>

<http://www.tuifly.com/>


Joose3
------

Joose3 is currently most active developing version of Joose. Its already stable with about 600 unit tests, though it may miss some features, 
presented in Joose2 (like type system). Instead of that Joose3 have some other features like roles implementation based on 
traits spec, better modularity and [mutability](http://openjsan.org/go/?l=Joose.Manual.Mutability).

Joose3 is also distributing via OpenJSAN platform, which enables further code re-use/modularity. 

which allows greatly simplify installation procedure (along with dependencies)   


ROADMAP
=======