Class('JooseIt.Widget.About', {
    
    isa : 'SymbieX.Template.Shotenjin.Container',
    
    does : [ 'Symbie.Widget', 'JooseIt.Widget.PageReport' ],

    
    have : {
        pageId                  : 'about',
        
        templateSources         : {
            /*tj:About.html
                <h1 id="whatisjooseabout">WHAT IS Joose About?</h1>
                
                <p>Joose is about Meta</p>
            tj*/

            /* GENERATED BY SHOTENJIN.JOOSED HELPER, DO NOT MODIFY DIRECTLY */
            sources : '<h1 id="whatisjooseabout">WHAT IS Joose About?</h1>\n<p>Joose is about Meta</p>'
        }
    }
    
})