Class('JooseIt.Widget.Download', {
    
    isa : 'SymbieX.Template.Shotenjin.Container',
    
    does : [ 'Symbie.Widget', 'JooseIt.Widget.PageReport' ],

    
    have : {
        pageId                  : 'download',
        
        templateSources         : {
            /*tj:Download.html
                <h1 id="download">Download</h1>
                
                <p>Current </p>
                
                <h2 id="jsan">JSAN</h2>
                
                <ul>
                <li><a href="http://openjsan.org/go/?l=Joose">Joose</a></li>
                </ul>
                
                <h2 id="gitrepository">Git Repository</h2>
                
                <ul>
                <li>You can grab a copy of the Joose <a href="http://github.com/Joose/Joose">repository at github</a></li>
                </ul>
            tj*/

            /* GENERATED BY SHOTENJIN.JOOSED HELPER, DO NOT MODIFY DIRECTLY */
            sources : '<h1 id="download">Download</h1>\n<p>Current </p>\n<h2 id="jsan">JSAN</h2>\n<ul>\n<li><a href="http://openjsan.org/go/?l=Joose">Joose</a></li>\n</ul>\n<h2 id="gitrepository">Git Repository</h2>\n<ul>\n<li>You can grab a copy of the Joose <a href="http://github.com/Joose/Joose">repository at github</a></li>\n</ul>'
        }
    }
    
})