Class('JooseIt.Widget.Footer', {
    
    isa : 'SymbieX.Template.Shotenjin.Container',
    
    
    have : {
        templateSources         : {
            /*tj:../../../templates/footer.tj.html
                ©2009-2010 Nickolay Platonovtj*/

            /* GENERATED BY SHOTENJIN.JOOSED HELPER, DO NOT MODIFY DIRECTLY */
            sources : '©2009-2010 Nickolay Platonov'
        }
    }
    
})