Class('JooseIt.Widget.Footer', {
    
    isa : 'SymbieX.Template.Shotenjin.Container',
    
    
    have : {
        templateSources         : {
            /*tj:../../../templates/footer.tj.html
                ©2009-2010 <a href="mailto:nickolay8@gmail.com">Nickolay Platonov</a>tj*/

            /* GENERATED BY SHOTENJIN.JOOSED HELPER, DO NOT MODIFY DIRECTLY */
            sources : '©2009-2010 <a href="mailto:nickolay8@gmail.com">Nickolay Platonov</a>'
        }
    }
    
})