RESOURCES
=========

Documentation
-------------

Manual: <http://openjsan.org/go/?l=Joose.Manual>

Cookbook: <http://openjsan.org/go/?l=Joose.Cookbook>


Community
---------

Mailing list: http://groups.google.com/group/joose-js

Forum: http://joose.it/forum

IRC: #joose on freenode


Blogs
-----

Malte Ubl: http://www.nonblocking.io/



Core extensions
---------------

Additional features for attributes: <http://openjsan.org/go/?l=JooseX.Attribute>

Dependencies (browser orientated): <http://openjsan.org/go/?l=JooseX.Namespace.Depended>