Class('JooseIt.Widget.Resources', {
    
    isa : 'SymbieX.Template.Shotenjin.Container',
    
    does : [ 'Symbie.Widget', 'JooseIt.Widget.PageReport' ],

    
    have : {
        pageId                  : 'contacts',
        
        templateSources         : {
            /*tj:Resources.html
                <h1 id="resourcesaboutjoose">RESOURCES ABOUT JOOSE</h1>
                
                <h2 id="community">Community</h2>
                
                <p>Mailing list, forum, irc..</p>
                
                <h2 id="blogs">Blogs</h2>
                
                <h2 id="articles">Articles</h2>
                
                <h2 id="extensions">Extensions</h2>
            tj*/

            /* GENERATED BY SHOTENJIN.JOOSED HELPER, DO NOT MODIFY DIRECTLY */
            sources : '<h1 id="resourcesaboutjoose">RESOURCES ABOUT JOOSE</h1>\n<h2 id="community">Community</h2>\n<p>Mailing list, forum, irc..</p>\n<h2 id="blogs">Blogs</h2>\n<h2 id="articles">Articles</h2>\n<h2 id="extensions">Extensions</h2>'
        }
    }
    
})