RESOURCES
=========

Documentation
-------------

Joose2 manual & cookbook: <http://code.google.com/p/joose-js/>

Joose3 manual: <http://openjsan.org/go/?l=Joose.Manual>

Joose3 cookbook: <http://openjsan.org/go/?l=Joose.Cookbook>


Community
---------

Mailing list: <http://groups.google.com/group/joose-js>

Forum: <http://joose.it/forum>

IRC: #joose on freenode


Blogs
-----

Malte Ubl: <http://www.nonblocking.io/>



Core extensions
---------------

Additional features for attributes: <http://openjsan.org/go/?l=JooseX.Attribute>

Dependencies (browser orientated): <http://openjsan.org/go/?l=JooseX.Namespace.Depended>