Class('JooseIt.Widget.Resources', {
    
    isa : 'SymbieX.Template.Shotenjin.Container',
    
    does : [ 'Symbie.Widget', 'JooseIt.Widget.PageReport' ],

    
    have : {
        pageId                  : 'resources',
        
        templateSources         : {
            /*tj:Resources.html
                <h1 id="resources">RESOURCES</h1>
                
                <h2 id="documentation">Documentation</h2>
                
                <p>Manual: <a href="http://openjsan.org/go/?l=Joose.Manual">http://openjsan.org/go/?l=Joose.Manual</a></p>
                
                <p>Cookbook: <a href="http://openjsan.org/go/?l=Joose.Cookbook">http://openjsan.org/go/?l=Joose.Cookbook</a></p>
                
                <h2 id="community">Community</h2>
                
                <p>Mailing list: <a href="http://groups.google.com/group/joose-js">http://groups.google.com/group/joose-js</a></p>
                
                <p>Forum: <a href="http://joose.it/forum">http://joose.it/forum</a></p>
                
                <p>IRC: #joose on freenode</p>
                
                <h2 id="blogs">Blogs</h2>
                
                <p>Malte Ubl: <a href="http://www.nonblocking.io/">http://www.nonblocking.io/</a></p>
                
                <h2 id="coreextensions">Core extensions</h2>
                
                <p>Additional features for attributes: <a href="http://openjsan.org/go/?l=JooseX.Attribute">http://openjsan.org/go/?l=JooseX.Attribute</a></p>
                
                <p>Dependencies (browser orientated): <a href="http://openjsan.org/go/?l=JooseX.Namespace.Depended">http://openjsan.org/go/?l=JooseX.Namespace.Depended</a></p>
            tj*/

            /* GENERATED BY SHOTENJIN.JOOSED HELPER, DO NOT MODIFY DIRECTLY */
            sources : '<h1 id="resources">RESOURCES</h1>\n<h2 id="documentation">Documentation</h2>\n<p>Manual: <a href="http://openjsan.org/go/?l=Joose.Manual">http://openjsan.org/go/?l=Joose.Manual</a></p>\n<p>Cookbook: <a href="http://openjsan.org/go/?l=Joose.Cookbook">http://openjsan.org/go/?l=Joose.Cookbook</a></p>\n<h2 id="community">Community</h2>\n<p>Mailing list: <a href="http://groups.google.com/group/joose-js">http://groups.google.com/group/joose-js</a></p>\n<p>Forum: <a href="http://joose.it/forum">http://joose.it/forum</a></p>\n<p>IRC: #joose on freenode</p>\n<h2 id="blogs">Blogs</h2>\n<p>Malte Ubl: <a href="http://www.nonblocking.io/">http://www.nonblocking.io/</a></p>\n<h2 id="coreextensions">Core extensions</h2>\n<p>Additional features for attributes: <a href="http://openjsan.org/go/?l=JooseX.Attribute">http://openjsan.org/go/?l=JooseX.Attribute</a></p>\n<p>Dependencies (browser orientated): <a href="http://openjsan.org/go/?l=JooseX.Namespace.Depended">http://openjsan.org/go/?l=JooseX.Namespace.Depended</a></p>'
        }
    }
    
})